import { cn } from "@/utils/cn";
import type { Metadata } from "next";
import { POPPINS, ROBOTO_MONO } from "@/config/fonts";
import { Toaster } from "react-hot-toast";
import "@/styles/index.css";

export const metadata: Metadata = {
  title: "Halu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "scroll-smooth bg-red-200",
        POPPINS.variable,
        ROBOTO_MONO.variable
      )}
    >
      <body className="flex flex-col w-screen max-w-screen h-full min-h-screen">
        <Toaster />
        {children}
      </body>
    </html>
  );
}
