import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { POPPINS, ROBOTO_MONO } from "@/config/fonts";
import { cn } from "@/utils/cn";
import "@/styles/index.css";
import { Providers } from "@/components/sections/providers";

export const metadata: Metadata = {
  title: "Halu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("scroll-smooth bg-light", POPPINS.variable, ROBOTO_MONO.variable)}>
      <body className="flex flex-col items-center w-full h-full min-h-screen">
        <div className="flex justify-center items-center max-w-2xl w-full p-20">
          <Toaster />
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
